import type { CatalogMeta } from "./types";

// Curated presentation metadata for each rated catalog. Mirrors the
// META object in app/demo.html. RRE data is merged onto this in
// lib/ratings.ts to produce a Listing.
export const CATALOG_META: Record<string, CatalogMeta> = {
  "evergreen-001": {
    title: "Suliko",
    artist: "Hamlet Gonashvili",
    genre: "Traditional",
    initials: "SU",
    grad: ["#7f1d1d", "#b45309"],
    price: 0.85,
    description:
      "A 1949 Georgian art song widely recorded since the early 1900s. Steady evergreen catalog with 21 years of streaming history across six platforms; revenue distribution well-diversified geographically. Long, predictable tail with low single-platform exposure.",
    catalog_age_months: 252,
    artist_age_years: 35,
    history_months: 240,
    platforms: 6,
    territories: 7,
    rows: 10080,
  },
  "balanced-001": {
    title: "Tbiliso",
    artist: "Revaz Laghidze",
    genre: "Jazz · Retro",
    initials: "TB",
    grad: ["#1e3a8a", "#c2410c"],
    price: 0.55,
    description:
      "Mid-1960s jazz-orchestra standard, the de facto musical signature of Tbilisi. Stable catalog spanning 8 years of digital revenue history with moderate platform diversification. Modest historical volatility; predictable distribution-cycle income.",
    catalog_age_months: 96,
    artist_age_years: 14,
    history_months: 96,
    platforms: 5,
    territories: 6,
    rows: 2880,
  },
  "active-pop-001": {
    title: "Nine Million Bicycles",
    artist: "Katie Melua",
    genre: "Pop",
    initials: "9M",
    grad: ["#831843", "#db2777"],
    price: 0.35,
    description:
      "International pop hit by Katie Melua, released 2005. Active-catalog phase with four years of recent streaming history; revenue trending downward as the song ages out of editorial rotation. Strong mid-decay; sync-licensing potential.",
    catalog_age_months: 48,
    artist_age_years: 6,
    history_months: 48,
    platforms: 4,
    territories: 5,
    rows: 960,
  },
  "high-hhi-001": {
    title: "Chito Gvrito",
    artist: "Vakhtang Kikabidze",
    genre: "Folk · Pop",
    initials: "CG",
    grad: ["#3f3f46", "#a16207"],
    price: 0.22,
    description:
      "Folk-pop classic by Vakhtang Kikabidze. 5 years of streaming history with revenue concentrated heavily on one platform — significant single-DSP exposure if Spotify changes its recommendation algorithms or licensing terms. High HHI flag.",
    catalog_age_months: 60,
    artist_age_years: 8,
    history_months: 60,
    platforms: 3,
    territories: 3,
    rows: 540,
  },
  "new-release-001": {
    title: "Argasvene",
    artist: "Mgzavrebi",
    genre: "Alt Rock",
    initials: "AR",
    grad: ["#0f766e", "#475569"],
    price: 0.18,
    description:
      "Recent alt-rock release from Mgzavrebi. Less than two years of streaming data; revenue trajectory unproven, viral-event dependent. Wide forecast confidence intervals reflect early-catalog uncertainty. Speculative tier, growth-tranche only.",
    catalog_age_months: 18,
    artist_age_years: 2,
    history_months: 18,
    platforms: 4,
    territories: 4,
    rows: 288,
  },
  "evergreen-002": {
    title: "Khasanbegura",
    artist: "Rustavi Ensemble",
    genre: "Polyphonic Folk",
    initials: "KH",
    grad: ["#581c87", "#1e3a8a"],
    price: 0.65,
    description:
      "A 19th-century western Georgian polyphonic war song, performed here by the Rustavi Ensemble — Georgia's most internationally recognized vocal group. Deep evergreen catalog with persistent classical and world-music revenue across institutional and consumer channels.",
    catalog_age_months: 192,
    artist_age_years: 56,
    history_months: 156,
    platforms: 5,
    territories: 6,
    rows: 5460,
  },
  "catalog-001": {
    title: "Iavnana",
    artist: "Nino Katamadze & Insight",
    genre: "Jazz · Folk",
    initials: "IA",
    grad: ["#365314", "#b45309"],
    price: 0.42,
    description:
      "Georgian jazz pianist Nino Katamadze's reinterpretation of the traditional Iavnana lullaby. Crossover audience — folk traditionalists plus the international jazz festival circuit. Seven years of digital revenue history, moderate platform diversification.",
    catalog_age_months: 96,
    artist_age_years: 22,
    history_months: 84,
    platforms: 5,
    territories: 5,
    rows: 1620,
  },
  "active-pop-002": {
    title: "Bedi",
    artist: "Iruli",
    genre: "Indie Pop",
    initials: "BE",
    grad: ["#7f1d1d", "#1e1b4b"],
    price: 0.28,
    description:
      "Recent indie-pop hit by Tbilisi-based Iruli. Strong initial streaming momentum across Caucasus markets and a TikTok crossover during 2024. Exponential decay phase with active editorial-playlist support; meaningful platform-concentration risk if Spotify rotation shifts.",
    catalog_age_months: 36,
    artist_age_years: 5,
    history_months: 36,
    platforms: 4,
    territories: 4,
    rows: 540,
  },
};
