import type { CatalogMeta } from "./types";

// Curated presentation metadata for each rated catalog. Mirrors the
// META object in app/demo.html. RRE data is merged onto this in
// lib/ratings.ts to produce a Listing.
export const CATALOG_META: Record<string, CatalogMeta> = {
  "evergreen-001": {
    title: "Suliko",
    artist: "Hamlet Gonashvili",
    genre: "Traditional",
    initials: "SU",
    grad: ["#7f1d1d", "#b45309"],
    price: 0.85,
    catalog_age_months: 252,
    artist_age_years: 35,
    history_months: 240,
    platforms: 6,
    territories: 7,
    rows: 10080,
  },
  "balanced-001": {
    title: "Tbiliso",
    artist: "Revaz Laghidze",
    genre: "Jazz · Retro",
    initials: "TB",
    grad: ["#1e3a8a", "#c2410c"],
    price: 0.55,
    catalog_age_months: 96,
    artist_age_years: 14,
    history_months: 96,
    platforms: 5,
    territories: 6,
    rows: 2880,
  },
  "active-pop-001": {
    title: "Nine Million Bicycles",
    artist: "Katie Melua",
    genre: "Pop",
    initials: "9M",
    grad: ["#831843", "#db2777"],
    price: 0.35,
    catalog_age_months: 48,
    artist_age_years: 6,
    history_months: 48,
    platforms: 4,
    territories: 5,
    rows: 960,
  },
  "high-hhi-001": {
    title: "Chito Gvrito",
    artist: "Vakhtang Kikabidze",
    genre: "Folk · Pop",
    initials: "CG",
    grad: ["#3f3f46", "#a16207"],
    price: 0.22,
    catalog_age_months: 60,
    artist_age_years: 8,
    history_months: 60,
    platforms: 3,
    territories: 3,
    rows: 540,
  },
  "new-release-001": {
    title: "Argasvene",
    artist: "Mgzavrebi",
    genre: "Alt Rock",
    initials: "AR",
    grad: ["#0f766e", "#475569"],
    price: 0.18,
    catalog_age_months: 18,
    artist_age_years: 2,
    history_months: 18,
    platforms: 4,
    territories: 4,
    rows: 288,
  },
};
